general.import = ["/home/konrad/.config/alacritty/gruvbox_material_alacritty.yml"]
# startup_mode = "Maximized"

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 10

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[window]
#decorations = "None"
opacity = 0.95

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 10
y = 10
