---
- name: Workstation Setup
  hosts: localhost
  become: true
  gather_facts: yes

  tasks:
    
    - name: Pacman - Full system upgrade
      pacman:
        update_cache: yes
        upgrade: yes

    - name: Install stow
      pacman:
        name: stow
        state: present

    - name: Stow dotfiles
      command: stow -v -t ~ . --adopt
      args:
        chdir: "{{ playbook_dir }}/.."  # Go up one directory to dotfiles root
      register: stow_result

    - name: Show stow result
      debug:
        var: stow_result.stdout_lines

    - name: Install essential packages
      pacman:
        name:
          - tmux
          - telegram-desktop
          - zathura
          - zathura-pdf-poppler
          - bob
          - task
          - timew
          - taskwarrior-tui
        state: present

    - name: Ensure kewlfft.aur collection is installed
      ansible.builtin.command:
        cmd: ansible-galaxy collection install kewlfft.aur
      args:
        creates: ~/.ansible/collections/ansible_collections/kewlfft/aur

    - name: Create the `aur_builder` user
      become: yes
      ansible.builtin.user:
        name: aur_builder
        create_home: yes
        group: wheel

    - name: Allow the `aur_builder` user to run `sudo pacman` without a password
      become: yes
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/11-install-aur_builder
        line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
        create: yes
        mode: 0644
        validate: 'visudo -cf %s'
    
    - name: Install AUR packages
      become_user: aur_builder
      kewlfft.aur.aur:
        use: yay
        name:
          - vesktop
          - taskopen
          - tmuxinator




