---
- name: Workstation Setup
  hosts: localhost
  become: true
  gather_facts: yes

  tasks:
    
    - name: Pacman - Full system upgrade
      pacman:
        update_cache: yes
        upgrade: yes

    - name: Install stow
      pacman:
        name: stow
        state: present

    - name: Stow dotfiles
      command: stow -v -t ~ . --adopt
      args:
        chdir: "{{ playbook_dir }}/.."  # Go up one directory to dotfiles root
      register: stow_result

    - name: Show stow result
      debug:
        var: stow_result.stdout_lines

    - name: Install essential packages
      pacman:
        name:
          - tmux
          - tmuxinator
          - telegram-desktop
          - zathura
          - zathura-pdf-poppler
          - bob
          - task
          - timew
          - taskwarrior-tui
        state: present

    - name: Install AUR packages via pacman module using yay
      community.general.pacman:
        name:
          - vesktop
          - taskopen
        state: present
        executable: /usr/bin/yay

